using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Modelo
{
    ///////////////////////////////////////////////////////////
//  Cancion.cs
//  Implementation of the Class Cancion
//  Generated by Enterprise Architect
//  Created on:      23-oct-2012 11:50:06 p.m.
//  Original author: sebastian
///////////////////////////////////////////////////////////




public class Cancion {

	private string autor = "";
    private string codigo = "";
	//private archivo de sonido ejemplo;
    private string gradoDificultad = "";
    private string nombre = "";
	private int tempo;
	public List<Nota> notas;

	public Cancion()
    {
        notas = new List<Nota>();
	}

    public void agregarNota(Nota not)
    {
        notas.Add(not);
    }

    public int _tempo
    {
        get
        {
            return tempo;
        }
        set
        {
            tempo = value;
        }
    }

    //public int  tempo{ get; set; }


}//end Cancion
}
