///////////////////////////////////////////////////////////
//  Nota.cs
//  Implementation of the Class Nota
//  Generated by Enterprise Architect
//  Created on:      07-oct-2012 11:46:16 p.m.
//  Original author: sebastian
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using System.Linq;

namespace Modelo
{
public class Nota {

	private string duracion;
	private float frecuencia;
    //private  imagen;
	//public Cancion m_Cancion;
	private string nombre;
	public List<int> posicionMastilX;
    public List<int> posicionMastilY;
    public int posicionPart;
    public int posicionX;
    public int margenSigNota;
    public int indiceImagen;
    private string octava;

    public Nota(string nom, string oct, string dura)
    {
        nombre = nom;
        octava = oct;
        duracion = dura;
        posicionMastilX = new List<int>();
        posicionMastilY = new List<int>();

    }

	public string _duracion{
		get{
			return duracion;
		}
		set{
			duracion = value;
		}
	}

    public float _frecuencia
    {
        get
        {
            return frecuencia;
        }
        set
        {
            frecuencia = value;
        }
    }

    public string _nombre
    {
        get
        {
            return nombre;
        }
        set
        {
            nombre = value;
        }
    }

    /*public int[] _posicionMastil
    {
        get
        {
            return posicionMastil;
        }
        set
        {
            posicionMastil = value;
        }
    }*/

    public int _posicionPart
    {
        get
        {
            return posicionPart;
        }
        set
        {
            posicionPart = value;
        }
    }

    public string _octava
    {
        get
        {
            return octava;
        }
        set
        {
            octava = value;
        }
    }

}//end Nota
}