using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Modelo
{
    ///////////////////////////////////////////////////////////
    //  Usuario.cs
    //  Implementation of the Class Usuario
    //  Generated by Enterprise Architect
    //  Created on:      19-nov-2012 07:35:47 p.m.
    //  Original author: sebastian
    ///////////////////////////////////////////////////////////




    public class Usuario
    {
        public string id;
        private string contraseña;
        private string nombre;
        private string pais;

        public Usuario(string i, string nom, string cont, string p)
        {
            id = i;
            contraseña = cont;
            nombre = nom;
            pais = p;
        }

        ~Usuario()
        {

        }

        public virtual void Dispose()
        {

        }

        public string _contraseña
        {
            get
            {
                return contraseña;
            }
            set
            {
                contraseña = value;
            }
        }

        public string _nombre
        {
            get
            {
                return nombre;
            }
            set
            {
                nombre = value;
            }
        }

        public string _pais
        {
            get
            {
                return pais;
            }
            set
            {
                pais = value;
            }
        }

    }//end Usuario
}
